### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by Speykious**
Depends on #9.

### CODE REVIEW

**Comment by Speykious** [comment]
@fianathedevgirl is that alright for a minimal documentation? I even added an example of custom renderer that just prints something.

When I think about it, in the future I'll probably just create a proper example with actual rudimentary rendering code for that.

**Comment by fxtressia** [comment]
This is enough for now ^^


Let's get this merged

**Comment by Speykious** [comment]
Alright :D

**Comment by fxtressia** [comment]
Yes, I'd like to see more code examples. Especially those that are demonstrating less documented parts of Inochi2D, especially its specification.

In particular, I'd like to see demonstration for SimplePhysics once we get that done.

**Pull request merged**
